version: '3.1'

services:
  cowrie:
    build:
      context: .
      dockerfile: Dockerfile
    image: cowrie/cowrie:latest
    restart: always
    security_opt:
      - "no-new-privileges:true"
    entrypoint: |
      bash -c "
      chown -R 1000:1000 /cowrie/var/persistent_fs
      exec /cowrie/cowrie-env/bin/twistd -n cowrie
      "
    group_add:
      - "1000"
    networks:
      - cowrie-network
    ports:
      - "2222:2222"  # SSH honeypot exposed on port 2222 (host)
    volumes:
      - ./etc:/cowrie/cowrie-git/etc
      - ./logs:/cowrie/cowrie-git/var/log/cowrie
      - ./var:/cowrie/cowrie-git/var
    environment:
      COWRIE_MYSQL_DATABASE: bakCow
      COWRIE_MYSQL_HOST: mysql
      COWRIE_MYSQL_USERNAME: shizuka
      COWRIE_MYSQL_PASSWORD: haveANiceDay

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPa55
      MYSQL_DATABASE: bakCow
      MYSQL_USER: shizuka
      MYSQL_PASSWORD: haveANiceDay
    networks:
      - cowrie-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  cowrie-network:
    driver: bridge
